# Do not use tabs in configuration files
# This will either lead to parsing errors, or Jekyll will revert to the default settings. Use spaces instead.
source: .
destination: _site
url: http://martinbour.com
sass:
  sass_dir: _sass
defaults:
  -
    scope:
      path: ""
    values:
      layout: "main"