# Do not use tabs in configuration files
# This will either lead to parsing errors, or Jekyll will revert to the default settings. Use spaces instead.
source: .
destination: _site
url: http://martinbour.com
baseurl: "" # config.yml default variable. does not include hostname
basepath: "/"

instafeedpath: /bower_components/instafeed.js/instafeed.js
scripts_local: /assets/scripts/local
scripts: /assets/scripts

sass:
  sass_dir: _sass

defaults:
  -
    scope:
      path: ""
    values:
      layout: "main"